version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "http://4wheels-admin.s3-website.eu-central-1.amazonaws.com"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started
      - npm run build:prod
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/ermi-admin*'
  discard-paths: no
